"""
/**********************************************************
* Project Euler 002                                       *
***********************************************************
* Each new term in the Fibonacci sequence is generated by *
* adding the previous two terms. By starting with 1 and 2,*
* the first 10 terms will be:                             *
* 	1,2,3,5,8,13,21,34,55,89,...                          *
* By considering the terms in the Fibonacci sequence whose*
* values do not exceed four million, find the sun of the  *
* even-valued terms.                                      *
**********************************************************/
"""

number = 0
number2 = 1
number3 = 1
numbers = 0

while number < 4000000:
    if number % 2 == 0:
#        print number
        numbers += number
    number = number2
    number2 = number3
    number3 = number + number2
print "result: ", numbers