#include "HTMLWriter.h"
#include <fstream>
using namespace std;

HTMLWriter::HTMLWriter()
{
    // 디폴트 파일 이름 변경
    _fileName = "NoName.html";

    // 디폴트 폰트 지정
    _fontName = "굴림";
    _fontSize = 3;
    _fontColor = "black";
}

HTMLWriter::~HTMLWriter()
{

}

HTMLWriter::HTMLWriter(const string& fileName, const string& content) : DocWriter(fileName, content)
{
    // 디폴트 폰트 지정
    _fontName = "굴림";
    _fontSize = 3;
    _fontColor = "black";
}

void HTMLWriter::Write()
{
    // 파일 열기
    ofstream of(_fileName.c_str());

    // HTML 헤더 저장
    of << "<HTML><HEAD><TITLE>This document was generated by HTMLWriter</TITLE></HEAD><BODY>";
    of << "<H1>Content</H1>";

    // 폰트 태그 시작
    of << "<Font name='" << _fontName << "' size='" << _fontSize << "' color='" << _fontSize << "'>";

    // 텍스트 저장
    of << _content;

    // 폰트 태그 닫기
    of << "</FONT>";

    // HTML 마무리
    of << "</BODY></HTML";
}

// 폰트 지정
void HTMLWriter::SetFont(const string& fontName, int fontSize, const string& fontColor)
{
    _fontName = fontName;
    _fontSize = fontSize;
    _fontColor = fontColor;
}